// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATMurRW093qFyZj0BVJ7LVdSDG1YWkc6g',
    appId: '1:146512868816:web:52140b14d95ca80c1ff5d5',
    messagingSenderId: '146512868816',
    projectId: 'buddy-ai-4fe54',
    authDomain: 'buddy-ai-4fe54.firebaseapp.com',
    storageBucket: 'buddy-ai-4fe54.appspot.com',
    measurementId: 'G-WSMWXX96MF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxQHwSiZy0s2UxE7tnsf31lSz-mUzqkT4',
    appId: '1:146512868816:android:3aa0fe074939f12b1ff5d5',
    messagingSenderId: '146512868816',
    projectId: 'buddy-ai-4fe54',
    storageBucket: 'buddy-ai-4fe54.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAlM6C3npTf1JLCcQ9-leGf_Ik_TD0DdI',
    appId: '1:146512868816:ios:fd8865612e64b39e1ff5d5',
    messagingSenderId: '146512868816',
    projectId: 'buddy-ai-4fe54',
    storageBucket: 'buddy-ai-4fe54.appspot.com',
    iosClientId: '146512868816-4hrnveo7bcttgccv96jchj176rudba0f.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAlM6C3npTf1JLCcQ9-leGf_Ik_TD0DdI',
    appId: '1:146512868816:ios:fd8865612e64b39e1ff5d5',
    messagingSenderId: '146512868816',
    projectId: 'buddy-ai-4fe54',
    storageBucket: 'buddy-ai-4fe54.appspot.com',
    iosClientId: '146512868816-4hrnveo7bcttgccv96jchj176rudba0f.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
